<?php


namespace reclamationBundle\Repository;

/**
 * CategorieReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieReclamationRepository extends \Doctrine\ORM\EntityRepository
{

}