jardin_homepage:
    path:     /
    defaults: { _controller: JardinBundle:Default:index }
jardin_addc:
    path:     /AjouterCategoriePersonnel
    defaults: { _controller: JardinBundle:Categorie:addc }
jardin_listc:
    path:     /AfficherCategoriePersonnel
    defaults: { _controller: JardinBundle:Categorie:listc }
jardin_list:
    path:     /AfficherPersonnel
    defaults: { _controller: JardinBundle:Personnel:list }
jardin_listFront:
    path:     /AfficherPersonnelFront
    defaults: { _controller: JardinBundle:Personnel:listFront }
jardin_add:
    path:     /AjouterPersonnel
    defaults: { _controller: JardinBundle:Personnel:add }
jardin_supprime:
    path:     /SupprimerPersonnel/{id}
    defaults: { _controller: JardinBundle:Personnel:supprime }
jardin_modifie:
    path:     /ModifierPersonnel/{id}
    defaults: { _controller: JardinBundle:Personnel:modifie }
jardin_supprimec:
    path:     /SupprimerCategoriePersonnel/{id}
    defaults: { _controller: JardinBundle:Categorie:supprimec }
ajax_search:
    path:     /search
    defaults: { _controller: JardinBundle:Personnel:search }