jardin_homepage:
    path:     /
    defaults: { _controller: JardinBundle:Default:index }
jardin_addc:
    path:     /AjouterCategoriePersonnel
    defaults: { _controller: JardinBundle:Categorie:addc }
jardin_listc:
    path:     /AfficherCategoriePersonnel
    defaults: { _controller: JardinBundle:Categorie:listc }
jardin_list:
    path:     /AfficherPersonnel
    defaults: { _controller: JardinBundle:Personnel:list }
<<<<<<< HEAD
jardin_listFront1:
    path:     /AfficherPersonnelFront1/{categorie}
    defaults: { _controller: JardinBundle:Personnel:listFront1 }
=======
>>>>>>> 9c216b0b00143a319616303a9538bae4b4f9d770
jardin_listFront:
    path:     /AfficherPersonnelFront
    defaults: { _controller: JardinBundle:Personnel:listFront }
jardin_add:
    path:     /AjouterPersonnel
    defaults: { _controller: JardinBundle:Personnel:add }
jardin_supprime:
    path:     /SupprimerPersonnel/{id}
    defaults: { _controller: JardinBundle:Personnel:supprime }
jardin_modifie:
    path:     /ModifierPersonnel/{id}
    defaults: { _controller: JardinBundle:Personnel:modifie }
jardin_supprimec:
    path:     /SupprimerCategoriePersonnel/{id}
    defaults: { _controller: JardinBundle:Categorie:supprimec }
ajax_search:
    path:     /search
<<<<<<< HEAD
    defaults: { _controller: JardinBundle:Personnel:search }
list:
    path:     /list
    defaults: { _controller: JardinBundle:test:list }
pdf:
    path:     /pdf/{id}
    defaults: { _controller: JardinBundle:Personnel:pdf }
avis:
    path:     /avis/{id}
    defaults: { _controller: JardinBundle:Personnel:ajouteravis }
score:
    path:     /score/{id}
    defaults: { _controller: JardinBundle:Personnel:score }
=======
    defaults: { _controller: JardinBundle:Personnel:search }
>>>>>>> 9c216b0b00143a319616303a9538bae4b4f9d770
