cours_homepage:
    path:     /
    defaults: { _controller: coursBundle:Default:index }
AfficherCours:
    path:     /AfficherCours
    defaults: { _controller: coursBundle:Default:AfficherCours }
ajouterCours:
    path:     /ajouterCours
    defaults: { _controller: coursBundle:Default:AjouterCours }
ajoutercatCours:
    path:     /ajouterCatcours
    defaults: { _controller: coursBundle:Default:ajoutercat }
Affichcatcours:
    path:     /affichercat
    defaults: { _controller: coursBundle:Default:affichercategorie }
deletematiere:
    path:     /supp/{id}
    defaults: { _controller: coursBundle:Default:supprimercategorie }
deletecours:
    path:     /suppcours/{id}
    defaults: { _controller: coursBundle:Default:supprimercours }
modifiercours:
    path:     /modifiercours/{id}
    defaults: { _controller: coursBundle:Default:modifiercours }
ajouterevent:
    path:     /ajouterevent
    defaults: { _controller: coursBundle:Default:ajouterevent }
Afficherevent:
    path:     /afficherevent
    defaults: { _controller: coursBundle:Default:afficherevent }
deleteevent:
    path:     /suppevent/{id}
    defaults: { _controller: coursBundle:Default:supprimerevent }
modifierevent:
    path:     /modifierevent/{id}
    defaults: { _controller: coursBundle:Default:modifierevent }