evenement_homepage:
    path:     /
    defaults: { _controller: evenementBundle:Default:index }
eventafficherf:
    path:      /event
    defaults:  { _controller: evenementBundle:Default:affichfront }
eventafficherpassee:
    path:      /eventpassee
    defaults:  { _controller: evenementBundle:Default:affichfrontpassee }
afficherevent:
    path:     /afficherevent
    defaults: { _controller: evenementBundle:Default:afficherevent }
ajoutevent:
    path:     /ajouterevent
    defaults: { _controller: evenementBundle:Default:ajevent }
suppevent:
    path:     /supp/{id}
    defaults: { _controller: evenementBundle:Default:supprimerevent }
modifierevent:
    path:     /modifier/{id}
    defaults: { _controller: evenementBundle:Default:modifierevent }
event_ajoutParticipation:
    path:     /ajoutParticipation/{id}
    defaults: { _controller: evenementBundle:Participation:ajoutParticipation }
UserAfficheParticipation:
    path:     /UserAfficheParticipation
    defaults: { _controller: evenementBundle:Participation:UserAfficheParticipation }
UserDeleteParticipation:
    path:     /UserDeleteParticipation/{id}
    defaults: { _controller: evenementBundle:Participation:UserDeleteParticipation }

