reclamation:
    resource: "@reclamationBundle/Resources/config/routing.yml"
    prefix:   /aa
jardin:
    resource: "@JardinBundle/Resources/config/routing.yml"
    prefix:   /

evenement:
    resource: "@evenementBundle/Resources/config/routing.yml"

enfant:
    resource: "@enfantBundle/Resources/config/routing.yml"
    prefix:   /

plat:
    resource: "@platBundle/Resources/config/routing.yml"
    prefix:   /

cours:
    resource: "@coursBundle/Resources/config/routing.yml"
    prefix:   /

main:
    resource: "@mainBundle/Resources/config/routing.yml"
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
app:
    resource: '@AppBundle/Controller/'
    type: annotation

class:
    path:      /class
    defaults:  { _controller: mainBundle:main:class }
index:
    path:      /index
    defaults:  { _controller: mainBundle:main:index }
<<<<<<< HEAD
enfant:
=======
event:
    path:      /event
    defaults:  { _controller: mainBundle:main:event }
enfant1:
>>>>>>> 91147945d97ec11322679b489da67b8970354f86
    path:      /enfant
    defaults:  { _controller: mainBundle:main:enfant }
transport:
    path:      /transport
    defaults:  { _controller: mainBundle:main:transport }
inscritransport:
    path:      /inscritransport
    defaults:  { _controller: mainBundle:main:inscritransport }

personnel:
    path:      /personnel
    defaults:  { _controller: mainBundle:main:personnel }
repas:
    path:      /repas
    defaults:  { _controller: mainBundle:main:repas }
reclamation:
    path:      /reclamation
    defaults:  { _controller: mainBundle:main:reclamation }
histreclamation:
    path:      /histreclamation
    defaults:  { _controller: mainBundle:main:histreclamation }
eventdetail:
    path:      /eventdetail
    defaults:  { _controller: mainBundle:main:eventdetail }
#Back
listeEnfant:
    path:      /listeEnfant
    defaults:  { _controller: mainBundle:main:listeEnfant }
ajoutTransport:
    path:      /ajoutTransport
    defaults:  { _controller: mainBundle:main:ajoutTransport }
ajoutPlat:
    path:     /plat
    defaults: { _controller: platBundle:plat:ajouterPlat }
abonnec:
    path:     /abonnec
    defaults: { _controller: enfantBundle:AbonnementCantine:afficherAbon }
supp:
    path:     /supp/{id}
    defaults: { _controller: enfantBundle:AbonnementCantine:deleteAbon }
inscriC:
    path:     /inscriC
    defaults: { _controller: enfantBundle:AbonnementCantine:inscriAbon }

