<?php


namespace enfantBundle\Repository;

/**
 * enfantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParentRepository extends \Doctrine\ORM\EntityRepository
{
    public  function rechercheAbon($user)
    {$query=$this->getEntityManager()
        ->createQuery('select c from mainBundle:User c where c.role=:tit')
        ->setParameters(array('tit'=>$user));

        return $queri=$query->getResult();

    }
}