<?php
namespace evenementBundle\Repository;
/**
 * ParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEvent(){
        $query = $this->getEntityManager()->createQuery("SELECT c FROM evenementBundle:Event c ORDER BY c.date");
        return $query->getResult();
    }
    


}