<?php


namespace enfantBundle\Repository;

/**
 * enfantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonneRepository extends \Doctrine\ORM\EntityRepository
{
    public  function rechercheAbon($user)
    {$query=$this->getEntityManager()
        ->createQuery('select c from enfantBundle:Abonnec c where c.idParent=:tit')
        ->setParameters(array('tit'=>$user));

        return $queri=$query->getResult();

    }

    public function enfant($user)
    {$query=$this->getEntityManager()
        ->createQuery('select c from enfantBundle:Enfant c where c.idParent=:tit')
        ->setParameters(array('tit'=>$user));

        return $queri=$query->getResult();



    }
}